version: "3"

services:
  ipfs:
    image: ipfs/kubo:latest
    hostname: ipfs
    environment:
      IPFS_PROFILE: "server"
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./ipfs/staging:/export
      - ./ipfs/data:/data/ipfs

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: --deterministic --mnemonic "buffalo they brave owner merit oak buddy brown chapter program nut text" --port 8545
    ports:
      - "8545:8545"
